name: proyecto_desa_web
services:

  backend-proyecto:
    image: backend
    container_name: backend-proyecto
    build:
      context: ./backend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./backend:/backend
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}

  frontend-proyecto:
    image: frontend
    container_name: frontend-proyecto
    command: sh -c "npm install && npm start"
    build:
      context: ./frontend
    volumes:
      - ./frontend/:/frontend

  database-proyecto:
    image: database
    container_name: database-proyecto
    build:
      context: ./database
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - 5436:5432

  # Ahora hacemos el contenedor de data-source
  data-source-proyecto:
      image: data-source
      container_name: data-source-proyecto
      build:
        context: ./data-source
      command: sh -c "npm install && npm run dev"
      volumes:
        - ./data-source:/data-source
      environment:
        - PGDATABASE=${PGDATABASE}
        - PGUSER=${PGUSER}
        - PGPASSWORD=${PGPASSWORD}
        - PGHOST=${PGHOST}
      depends_on:
      - database-proyecto

  proxy-proyecto:
    image: proxy
    container_name: proxy-proyecto
    build: ./proxy
    ports:
      - 80:80
    depends_on:
      - frontend-proyecto
      - backend-proyecto
      - database-proyecto
      - data-source-proyecto
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
